[package]
name = "touch-n-drink"
version = "0.0.0"
authors = ["Andreas Neuhaus <git@zargony.com>"]
edition = "2021"
repository = "https://github.com/zargony/touch-n-drink"

[[bin]]
name = "touch-n-drink"
test = false
bench = false

[profile.dev]
# Rust debug code is slow, so always build with some optimization
opt-level = "s"

[profile.dev.package.esp-hal]
# Build esp-hal with release optimizations as it recommends
debug-assertions = false
opt-level = 3

[profile.dev.package.esp-wifi]
# Build esp-wifi with release optimizations as it recommends
debug-assertions = false
opt-level = 3

[profile.release]
# LLVM can perform better optimizations using a single thread
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = "s"
overflow-checks = false

[build-dependencies]
git2 = "0.19"

[dependencies]
display-interface = "0.5"
embassy-embedded-hal = "0.2"
embassy-executor = "0.5"
embassy-futures = "0.1"
embassy-sync = "0.6"
embassy-time = { version = "0.3", features = ["generic-queue"] }
embedded-graphics = "0.8"
embedded-hal-async = "1.0"
esp-backtrace = { version = "0.13", features = ["esp32c3", "custom-halt", "panic-handler", "exception-handler", "println"] }
esp-hal = { version = "0.19", features = ["esp32c3", "async"] }
esp-hal-embassy = { version = "0.2", features = ["esp32c3"] }
esp-println = { version = "0.10", features = ["esp32c3", "log"] }
esp-wifi = { version = "0.7", default-features = false, features = ["esp32c3", "async", "phy-enable-usb", "wifi"] }
log = { version = "0.4", features = ["release_max_level_info"] }
pn532 = "0.4"
static_cell = "2.1"
u8g2-fonts = "0.4"

# SSD1306 driver (>0.8.4) with embedded-hal-async 1.0 and display-interface 0.5 support
# See https://github.com/rust-embedded-community/ssd1306/pull/213
# and https://github.com/rust-embedded-community/ssd1306/pull/214
ssd1306 = { git = "https://github.com/rust-embedded-community/ssd1306", rev = "35ec056c11f2889dd519e554d710a70b37ccf682", features = ["async"] }
