[package]
name = "lsc-touch-n-drink"
version = "0.0.0"
authors = ["Andreas Neuhaus <git@zargony.com>"]
edition = "2021"
repository = "https://github.com/zargony/lsc-touch-n-drink"

[profile.dev]
# Rust debug code is slow, so always build with some optimization
opt-level = "s"

[profile.release]
# LLVM can perform better optimizations using a single thread
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = "s"
overflow-checks = false

[dependencies]
display-interface = "0.5"
display-interface-spi = "0.5"
embassy-executor = { version = "0.5", features = ["log"] }
embassy-time = { version = "0.3", features = ["generic-queue"] }
embedded-graphics = "0.8"
embedded-hal = "1.0"
embedded-hal-async = "1.0"
embedded-hal-bus = { version = "0.2", features = ["async"] }
esp-backtrace = { version = "0.12", features = ["esp32c3", "panic-handler", "exception-handler", "println"] }
esp-hal = { version = "0.18", features = ["esp32c3", "async", "log"] }
esp-hal-embassy = { version = "0.1", features = ["esp32c3", "time-timg0"] }
esp-println = { version = "0.9", features = ["esp32c3", "log"] }
esp-wifi = { version = "0.6", features = ["esp32c3", "async", "log", "phy-enable-usb", "wifi"] }
log = { version = "0.4", features = ["release_max_level_info"] }

# SSD1309 driver with embedded-hal 1.0 and display-interface 0.5 support
# See https://github.com/antonok-edm/ssd1309/pull/10
ssd1309 = { git = "https://github.com/antonok-edm/ssd1309", rev = "f2f4a60" }
