[package]
name = "touch-n-drink"
version = "0.2.0"
authors = ["Andreas Neuhaus <git@zargony.com>"]
edition = "2021"
description = "Firmware for cashless payment device for cold drinks at the aeroclub at EDLH"
repository = "https://github.com/zargony/touch-n-drink"
license = "MIT OR Apache-2.0"

[[bin]]
name = "touch-n-drink"
test = false
bench = false

[lints.clippy]
pedantic = "warn"

[profile.dev]
# Rust debug code is slow, so always build with some optimization
opt-level = "s"

[profile.dev.package.esp-hal]
# Build esp-hal with release optimizations as it recommends
debug-assertions = false
opt-level = 3

[profile.dev.package.esp-wifi]
# Build esp-wifi with release optimizations as it recommends
opt-level = 3
# Additionally turn off overflow checks as these seem to cause random esp-wifi panics
overflow-checks = false

[profile.release]
# LLVM can perform better optimizations using a single thread
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = "s"
overflow-checks = false

[build-dependencies]
git2 = { version = "0.20", default-features = false }

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["alloc"] }
const-hex = { version = "1.14", default-features = false }
display-interface = "0.5"
embassy-embedded-hal = "0.3"
embassy-executor = "0.7"
embassy-futures = "0.1"
embassy-net = { version = "0.6", features = ["dhcpv4", "dns", "proto-ipv4", "tcp"] }
embassy-sync = "0.6"
embassy-time = "0.4"
embedded-graphics = "0.8"
embedded-hal-async = "1.0"
embedded-io-async = { version = "0.6", features = ["alloc"] }
embedded-storage = "0.3"
esp-alloc = "0.6"
esp-backtrace = { version = "0.15", features = ["esp32c3", "custom-halt", "panic-handler", "exception-handler", "println"] }
esp-hal = { version = "0.23", features = ["esp32c3"] }
esp-hal-embassy = { version = "0.6", features = ["esp32c3"] }
esp-partition-table = "0.1"
esp-println = { version = "0.13", features = ["esp32c3", "log"] }
esp-storage = { version = "0.4", features = ["esp32c3"] }
esp-wifi = { version = "0.12", default-features = false, features = ["esp32c3", "esp-alloc", "log", "wifi"] }
log = { version = "0.4", features = ["release_max_level_info"] }
pn532 = "0.4"
rand_core = "0.6"
reqwless = { version = "0.13", default-features = false, features = ["alloc", "embedded-tls"] }
ssd1306 = { version = "0.9", features = ["async"] }
u8g2-fonts = "0.4"

# FIXME: Pin maybe-async-cfg to 0.2.4 since 0.2.5 breaks ssd1306
# See https://github.com/rust-embedded-community/ssd1306/issues/219
# and https://github.com/rust-embedded-community/ssd1306/commit/f3a2f7aca421fbf3ddda45ecef0dfd1f0f12330e
maybe-async-cfg = "=0.2.4"

[features]
default = []
# Enable additional logging of dependencies
log = [
    "embassy-executor/log", "embassy-net/log", "embassy-sync/log", "embassy-time/log",
    "esp-hal/log", "esp-hal-embassy/log", "reqwless/log",
]
