name: CI
on:
  push:
    paths:
      - .github/workflows/ci.yaml
      - "firmware/**"
  pull_request:
    paths:
      - .github/workflows/ci.yaml
      - "firmware/**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: &matrix
        chip:
          - esp32c3
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv32imac-unknown-none-elf, riscv32imc-unknown-none-elf
          components: clippy, rustfmt
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Cache cargo data
        uses: actions/cache@v5
        with:
          # See https://doc.rust-lang.org/stable/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
          path: |
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
          key: cargo-${{ runner.os }}
      - name: Check formatting
        run: cargo fmt --all --check
        working-directory: firmware
      - name: Clippy
        run: cargo xtask clippy --chip ${{ matrix.chip }} -- --deny warnings --allow deprecated
        working-directory: firmware

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Cache cargo data
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
          key: cargo-${{ runner.os }}
      - name: Run tests
        run: cargo test
        working-directory: firmware

  build:
    name: Build
    needs: [check, test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: *matrix
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv32imac-unknown-none-elf, riscv32imc-unknown-none-elf
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Cache cargo data
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
          key: cargo-${{ runner.os }}
      - name: Cache espflash
        id: cache-espflash
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/espflash
          key: espflash-${{ runner.os }}
      - name: Install espflash
        if: steps.cache-espflash.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config libudev-dev
          cargo install --locked espflash
      - name: Build firmware
        run: cargo xtask build --chip ${{ matrix.chip }} --release
        working-directory: firmware
      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: touch-n-drink-${{ matrix.chip }}-elf
          path: |
            firmware/target/release/images/touch-n-drink-${{ matrix.chip }}.elf
          if-no-files-found: error
      - name: Upload image artifact
        uses: actions/upload-artifact@v6
        with:
          name: touch-n-drink-${{ matrix.chip }}
          path: |
            firmware/target/release/images/touch-n-drink-${{ matrix.chip }}*.bin
            firmware/target/release/images/touch-n-drink-${{ matrix.chip }}*.sha256
          if-no-files-found: error

  release:
    name: Release
    permissions:
      contents: write
    needs: [build]
    if: github.repository == 'zargony/touch-n-drink' && startsWith(github.ref, 'refs/tags/firmware-')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            firmware/CHANGELOG.md
      - name: Download all build artifacts
        uses: actions/download-artifact@v7
        with:
          path: firmware/images
          merge-multiple: true
      - name: Aggregate checksums
        run: |
          cat images/touch-n-drink-*.sha256 >images/SHA256SUMS
          cd images && shasum -a 256 -c SHA256SUMS
        working-directory: firmware
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: firmware/CHANGELOG.md
          draft: true
          files: |
            firmware/images/touch-n-drink-*.bin
            firmware/images/SHA256SUMS
          fail_on_unmatched_files: true
